---
- name: install lamp 
  hosts: all
  become: yes
  tasks:
    - name: update ubuntu
      ansible.builtin.apt:
        name: ubuntu
        update_cache: yes
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: install php
      ansible.builtin.apt:
        name: 
          - php 
          - libapache2-mod-php 
          - php-mysql 
        state: present     