---
- name: install apache and phpinfo
  hosts: all
  become: yes
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present 
    - name: install php
      ansible.builtin.apt:
        name: 
          - php 
          - libapache2-mod-php 
          - php-mysql
        state: present    
    - name: copy phpinfo to html page
      ansible.builtin.copy:
        dest: /var/www/html/info.php
        content:
          '<?php
            phpinfo();
            ?>'

