---
- name: extract files from tomcat 
  ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-10.0.27.tar.gz
        dest: /opt/tomcat/
        remote_src: yes
- name: change directory ownership
  ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        recurse: yes  
- name: change shell file permissions
  ansible.builtin.file:
        path: /opt/tomcat/latest/bin/
        owner: tomcat
        group: tomcat
        mode: '+x'
  with_items: "{{ files_to_change }}"   
