---
- name: install jboss on ubuntu
  hosts: all
  become: yes
  vars:
    java_package: openjdk-11-jdk
    wildfly_download_url: https://github.com/wildfly/wildfly/releases/download/27.0.1.Final/wildfly-27.0.1.Final.tar.gz
    wildfly_destination: /tmp/ 
    wildfly_group: wildfly
    wildfly_user: wildfly
  tasks:
    - name: install java 
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present 
      tags:
        - devops 
        - azure   
    - name: create directory
      ansible.builtin.file:
        path: /opt/wildfly 
        state: directory   
      tags: 
        - devops 
        - aws   
    - name: download wildlife version
      ansible.builtin.get_url:
        url: "{{ wildfly_download_url }}"
        dest: "{{ wildfly_destination }}"    
      notify:
        - unzip files 
      tags: 
        - devops       
    - name: add group
      ansible.builtin.group:
        name: "{{ wildfly_group }}"
        system: true
        state: present
    - name: useradd
      ansible.builtin.user:
        name: "{{ wildfly_user }}"
        shell: /sbin/nologin
        group: "{{ wildfly_group }}"
        system: true
        home: /opt/wildfly        
    - name: create file
      ansible.builtin.file:
        path: /etc/wildfly
        state: directory
    - name: copy files to wildfly
      ansible.builtin.copy:   
        src: /opt/wildfly/wildfly-27.0.1.Final/docs/contrib/scripts/systemd/wildfly.conf
        dest: /etc/wildfly/
        remote_src: yes
        owner: wildfly
        group: wildfly
        mode: '0777'
    - name: copy folder 
      ansible.builtin.copy:
        src: /opt/wildfly/wildfly-27.0.1.Final/ 
        dest: /opt/wildfly/   
        remote_src: yes   
    - name: copyfiles to system 
      ansible.builtin.copy: 
        src: /opt/wildfly/wildfly-27.0.1.Final/docs/contrib/scripts/systemd/wildfly.service
        dest: /etc/systemd/system/
        remote_src: yes
    - name: copyfiles to bin 
      ansible.builtin.copy:
        src: /opt/wildfly/wildfly-27.0.1.Final/docs/contrib/scripts/systemd/launch.sh
        dest: /opt/wildfly/bin/
        remote_src: yes
    - name: change ownership
      ansible.builtin.file:
        path: /opt/wildfly
        state: directory
        recurse: yes
        owner: wildfly
        group: wildfly
        mode: '0777'
      notify:
        - file permissions
    - name: system restart  
      ansible.builtin.systemd:
        daemon_reload: yes
        name: wildfly
        enabled: yes
        state: started    
  handlers:   
    - name: unzip files
      ansible.builtin.unarchive:
        src: /tmp/wildfly-27.0.1.Final.tar.gz
        remote_src: yes
        dest: /opt/wildfly/
        mode: '0777' 
    - name: file permissions
      ansible.builtin.find:
        paths: /opt/wildfly/bin/
        patterns: "*.sh"
      register: files_to_change    
         
                
    
            
