pipeline {
    agent { label 'ansible' }
    stages {
        stage('vcs') {
            steps {
                git url: 'https://github.com/Nagaraju11111/ansible.git',
                    branch: 'master'
            }
        }
        stage('ansible') {
            steps {
                ansiblePlaybook(
                    playbook: './tomcat2/handlers.yaml',
                    become: true
                    inventory: './tomcat2/hosts'
             )
               //* sh 'ansible-playbook -i ./tomcat2/hosts ./tomcat2/handlers.yaml'*//
            }
        }
    }
}