---
- name: install tomcat on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install java 
      ansible.builtin.debug:
        msg: installing java11 on ubuntu server
    - name: install java and update ubuntu 
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes 
        state: present
    - name: create tomcat group 
      ansible.builtin.debug:
        msg: creating tomcat group 
    - name: create tomcat group
      ansible.builtin.group:
        name: tomcat 
        state: present        
    - name: create tomcat user
      ansible.builtin.debug:
        msg: creating tomcat user    
    - name: create a tomcat user
      ansible.builtin.user:
        name: tomcat 
        home: /opt/tomcat 
        shell: /bin/false 
        system: true 
        group: tomcat 
    - name: download tomcat 
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz
        dest: /tmp/ 
    - name: extract files from tomcat 
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-10.0.27.tar.gz
        dest: /opt/tomcat/
        remote_src: yes 
    - name: cretae a symbolic link 
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.0.27
        dest: /opt/tomcat/latest
        owner: tomcat 
        group: tomcat 
        state: link  
    - name: change directory ownership
      ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        recurse: yes
    - name: select all shell files 
      ansible.builtin.find: 
        paths: /opt/tomcat/latest/bin/
        patterns: '*.sh'
      register: files_to_change 
    - name: chnage shell file permissions
      ansible.builtin.file:
        path: /opt/tomcat/latest/bin/
        owner: tomcat
        group: tomcat
        mode: '+x'
      with_items: "{{ files_to_change }}"   
    - name: copy service files 
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        mode: '777'
    - name: start tomcat service
      ansible.builtin.systemd:
        name: tomcat 
        daemon_reload: yes
        enabled: yes
        state: started                             