---
- name: install jenkins on ubuntu
  hosts: all 
  become: yes
  tasks:
    - name: install java
      ansible.builtin.apt: 
        name: openjdk-11-jdk 
        update_cache: yes 
        state: present 
    - name: wget in jenkins 
      ansible.builtin.get_url: 
        url: https://updates.jenkins.io/download/war/2.385/jenkins.war 
        dest: /home/devops/
    - name: copy servicefile
      ansible.builtin.copy: 
        src: jenkins.service 
        dest: /etc/systemd/system/jenkins.service
    - name: service file 
      ansible.builtin.systemd: 
        name: jenkins 
        state: started    
        enabled: yes
